import { colorDistanceSq, type RGB } from "./color";

export interface NamedColor {
  name: string;
  hex: string;
}

export const COLOR_NAME_TABLE: NamedColor[] = [
  { name: "Black", hex: "#000000" },
  { name: "Ink Black", hex: "#12110f" },
  { name: "Obsidian", hex: "#1b1b1d" },
  { name: "Charcoal", hex: "#333333" },
  { name: "Graphite", hex: "#48494b" },
  { name: "Slate Gray", hex: "#62666a" },
  { name: "Mid Gray", hex: "#808080" },
  { name: "Dove Gray", hex: "#a5a5a2" },
  { name: "Silver", hex: "#c0c0c0" },
  { name: "Mist", hex: "#d9dcda" },
  { name: "Porcelain", hex: "#ecebe7" },
  { name: "White", hex: "#ffffff" },
  { name: "Warm White", hex: "#faf7f0" },
  { name: "Cream", hex: "#fff4cf" },
  { name: "Ivory", hex: "#ffffe8" },
  { name: "Sand", hex: "#d8c4a2" },
  { name: "Oatmeal", hex: "#cbbfa8" },
  { name: "Taupe", hex: "#8b7d6b" },
  { name: "Mushroom", hex: "#9b8f80" },
  { name: "Stone", hex: "#8a8880" },
  { name: "Espresso", hex: "#3a241b" },
  { name: "Chocolate", hex: "#5b3524" },
  { name: "Walnut", hex: "#704b35" },
  { name: "Chestnut", hex: "#8b4a2f" },
  { name: "Cocoa", hex: "#765044" },
  { name: "Caramel", hex: "#b9783e" },
  { name: "Camel", hex: "#c19a6b" },
  { name: "Tan", hex: "#d2a679" },
  { name: "Khaki", hex: "#b6a66b" },
  { name: "Red", hex: "#ff0000" },
  { name: "Crimson", hex: "#c8102e" },
  { name: "Scarlet", hex: "#e63b2e" },
  { name: "Cherry", hex: "#b82235" },
  { name: "Ruby", hex: "#9f1239" },
  { name: "Oxblood", hex: "#5c1a1b" },
  { name: "Brick Red", hex: "#a44736" },
  { name: "Terracotta", hex: "#c86b4a" },
  { name: "Rust", hex: "#a64b2a" },
  { name: "Coral", hex: "#ff7f66" },
  { name: "Salmon", hex: "#ed8a80" },
  { name: "Blush", hex: "#e8b4ad" },
  { name: "Dusty Rose", hex: "#c98f99" },
  { name: "Rose", hex: "#df6f91" },
  { name: "Hot Pink", hex: "#ff4f9a" },
  { name: "Fuchsia", hex: "#d91e8a" },
  { name: "Raspberry", hex: "#b52b63" },
  { name: "Wine", hex: "#722f4b" },
  { name: "Burgundy", hex: "#6d213c" },
  { name: "Orange", hex: "#ff7a00" },
  { name: "Tangerine", hex: "#f28522" },
  { name: "Apricot", hex: "#f4b183" },
  { name: "Peach", hex: "#ffc5a1" },
  { name: "Papaya", hex: "#f59d62" },
  { name: "Copper", hex: "#b66a3c" },
  { name: "Amber", hex: "#d88913" },
  { name: "Gold", hex: "#d4af37" },
  { name: "Marigold", hex: "#e5a823" },
  { name: "Yellow", hex: "#ffff00" },
  { name: "Lemon", hex: "#f5e642" },
  { name: "Butter", hex: "#f5dfa0" },
  { name: "Vanilla", hex: "#f3e5ab" },
  { name: "Mustard", hex: "#c49a24" },
  { name: "Ochre", hex: "#b7791f" },
  { name: "Chartreuse", hex: "#b7e000" },
  { name: "Green", hex: "#00ff00" },
  { name: "Forest Green", hex: "#1f5c3a" },
  { name: "Pine", hex: "#244d3d" },
  { name: "Hunter Green", hex: "#355e3b" },
  { name: "Emerald", hex: "#148f5b" },
  { name: "Kelly Green", hex: "#3aaa35" },
  { name: "Grass", hex: "#68a33e" },
  { name: "Lime", hex: "#8bd13c" },
  { name: "Olive", hex: "#777b32" },
  { name: "Moss", hex: "#68784e" },
  { name: "Avocado", hex: "#78914b" },
  { name: "Sage", hex: "#9caf88" },
  { name: "Celadon", hex: "#b5cbb7" },
  { name: "Mint", hex: "#a8e6cf" },
  { name: "Seafoam", hex: "#76c7b7" },
  { name: "Teal", hex: "#167d7f" },
  { name: "Deep Teal", hex: "#105d60" },
  { name: "Aqua", hex: "#39d9d0" },
  { name: "Cyan", hex: "#00ffff" },
  { name: "Turquoise", hex: "#30b8b2" },
  { name: "Lagoon", hex: "#218c9c" },
  { name: "Petrol Blue", hex: "#285c68" },
  { name: "Blue", hex: "#0000ff" },
  { name: "Midnight Navy", hex: "#121d3f" },
  { name: "Navy", hex: "#172b55" },
  { name: "Prussian Blue", hex: "#173f5f" },
  { name: "Denim", hex: "#355f8a" },
  { name: "Cobalt", hex: "#2455c3" },
  { name: "Royal Blue", hex: "#3157d5" },
  { name: "Cornflower", hex: "#7298da" },
  { name: "Sky Blue", hex: "#79bce8" },
  { name: "Powder Blue", hex: "#b7d5e8" },
  { name: "Ice Blue", hex: "#d8edf2" },
  { name: "Periwinkle", hex: "#8f9ee7" },
  { name: "Indigo", hex: "#4b3f91" },
  { name: "Violet", hex: "#7952b3" },
  { name: "Purple", hex: "#8000c8" },
  { name: "Amethyst", hex: "#9b6bb4" },
  { name: "Lavender", hex: "#c7b5e6" },
  { name: "Lilac", hex: "#b99ac8" },
  { name: "Plum", hex: "#754668" },
  { name: "Aubergine", hex: "#4b2840" },
  { name: "Mauve", hex: "#aa7f9e" },
  { name: "Orchid", hex: "#c36ab1" },
  { name: "Magenta", hex: "#ff00ff" },
  { name: "Neon Pink", hex: "#ff2d95" },
  { name: "Mahogany", hex: "#6b3028" },
  { name: "Clay", hex: "#a66f5b" },
  { name: "Putty", hex: "#b8aa98" },
  { name: "Bone", hex: "#e5dccb" },
  { name: "Parchment", hex: "#e9ddc2" },
  { name: "Champagne", hex: "#ead6a8" },
  { name: "Honey", hex: "#d9a441" },
  { name: "Sunflower", hex: "#f4c430" },
  { name: "Acid Green", hex: "#b0f200" },
  { name: "Fern", hex: "#4f7942" },
  { name: "Eucalyptus", hex: "#5f8575" },
  { name: "Jade", hex: "#2f9c78" },
  { name: "Spruce", hex: "#2c5f5d" },
  { name: "Ocean", hex: "#237a9f" },
  { name: "Cerulean", hex: "#2a8ab8" },
  { name: "Azure", hex: "#2f80ed" },
  { name: "Ultramarine", hex: "#3347a8" },
  { name: "Blueberry", hex: "#3d477d" },
  { name: "Iris", hex: "#6b5eb5" },
  { name: "Heather", hex: "#8d729b" },
  { name: "Mulberry", hex: "#803f62" },
  { name: "Watermelon", hex: "#e85d75" },
  { name: "Flamingo", hex: "#ef8e9c" },
  { name: "Shell Pink", hex: "#f2d0c9" },
  { name: "Cloud", hex: "#f1f3f2" },
  { name: "Blue Gray", hex: "#71828f" },
  { name: "Green Gray", hex: "#7f8b7a" },
  { name: "Warm Gray", hex: "#938b82" },
  { name: "Cool Gray", hex: "#8b929a" },
];

const resolved = COLOR_NAME_TABLE.map((entry) => ({
  name: entry.name,
  color: hexToRgb(entry.hex),
}));

export function nearestColorName(rgb: RGB): string {
  let nearest = resolved[0];
  let distance = colorDistanceSq(rgb, nearest.color);
  for (let index = 1; index < resolved.length; index++) {
    const candidate = resolved[index];
    const candidateDistance = colorDistanceSq(rgb, candidate.color);
    if (candidateDistance < distance) {
      nearest = candidate;
      distance = candidateDistance;
    }
  }
  return nearest.name;
}

function hexToRgb(hex: string): RGB {
  return {
    r: Number.parseInt(hex.slice(1, 3), 16),
    g: Number.parseInt(hex.slice(3, 5), 16),
    b: Number.parseInt(hex.slice(5, 7), 16),
  };
}
